apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dj85
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-dj85@sha256:7cc38ddee28384454a56ae362235cb12b5947c305689d0f49ab2da627f6aaa6c
        name: my-nodejs
        resources: {}
status: {}
